sudo: required
language: go
go_import_path: github.com/colinmarc/hdfs
go: 1.x
env:
- PLATFORM=hdp2
- PLATFORM=cdh5
- PLATFORM=cdh6
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=authentication DATA_TRANSFER_PROTECTION=authentication
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=integrity DATA_TRANSFER_PROTECTION=integrity
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=privacy DATA_TRANSFER_PROTECTION=privacy
- PLATFORM=cdh6 KERBEROS=true RPC_PROTECTION=privacy DATA_TRANSFER_PROTECTION=privacy
  AES=true
before_install:
- export GO111MODULE=on
install:
- git clone https://github.com/sstephenson/bats $HOME/bats
- mkdir -p $HOME/bats/build
- "$HOME/bats/install.sh $HOME/bats/build"
- export PATH="$PATH:$HOME/bats/build/bin"
- "./travis-setup.sh $PLATFORM"
before_script:
- export HADOOP_CONF_DIR="/etc/hadoop/conf"
- find internal/protocol -name *.pb.go | xargs touch
script: make test
after_failure: find /var/log/hadoop-hdfs | xargs cat
before_deploy: make release
deploy:
  provider: releases
  api_key:
    secure: NUTDjrwc93HQRJSyVEuoNTpef1s+jT8NuPraISnPU0L1DsB9dWGpRJXNGc29Jo64KvoTTqqXfXTV6xaMpgdTP0sRF3P6CCaQn4Mxp0GWDQeu1BJE9o8xlrw76VeMFfnZh9JXhU5hu9yNJthaetHvA2py2cEj4y3WJ3HKgpS7j1kess+pFXyivDNLjitAipC4jQuxWgfA5ykv1p0JNS18DC9m9jpgNoapXLOCpMVXQzRykx+cZhy9Rj+dRiYx0cDg3CFym71dJepdMYj1OdH+J5k1NmUtaazOECb/XxjM3u9Y8/OUEgVCrpbRoGwtTFsW77lYeui2gt+vzW+whW75aAYqgPrZLPnSdHA09guDWLVjHixrdTw+iiDdWxLCon3rhn6VRRLEGnf6cW2SQgvEpYQAyadQOsjSHC7dCOyA2yZw1Y54ANZKfzYGZQHo+mBoUJtcGbfAfCQTklmEmmyN+jw8P6Vyf94A6Sj0hKvcYCnpW08IAh4tcJzEWmnlJJigpr+ayhIaHNl3MjdLZJIEyk4583Qr1CDt0wAeWVOXx+VjdZ0oJ8U0DzkvZrKfxIu4GxWBgYy8Fi4LSj7MYHTJuobH8nfnHUVqbOXHdCR+3utNe4T6EZZ8VFwWUB+s+uI5ZGCuviBtOB8B1wlEsXEJX/ElTu0FugIAINcROWUE7Io=
  file: gohdfs-*.tar.gz
  file_glob: true
  skip_cleanup: true
  on:
    repo: sknopp/hdfs
cache:
  directories:
  - "$HOME/.cache/go-build"
  - "$GOPATH/pkg/mod"
